services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-school-equipment-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:17
    depends_on:
      - db
    #ports:
    #  - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo-school-equipment-web-data:/var/lib/odoo
      - .:/mnt/extra-addons/school_equipment
    command: odoo -d odoo --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons -i school_equipment -u school_equipment --dev=reload
    restart: unless-stopped

volumes:
  odoo-school-equipment-db-data:
  odoo-school-equipment-web-data:
